import React from 'react';
import { 
  FaGamepad, 
  FaTshirt, 
  FaBook, 
  FaMusic, 
  FaMugHot,
  FaKey,
  FaUserAstronaut,
  FaGem,
  FaClock,
  FaCalendarAlt,
  FaGift,
  FaBox,
  FaFilm,
  FaFlask
} from 'react-icons/fa';

export const productsData = [
  {
    id: 1,
    name: "رزیدنت ایول ۴ - نسخه بازسازی‌شده",
    price: 59.99,
    category: "games",
    image: "https://image.api.playstation.com/vulcan/ap/rnd/202210/1913/7KWGfjFnK8t8PSCDwgBCyQ8O.png",
    description: "نسخه بازسازی‌شده بازی کلاسیک رزیدنت ایول ۴ با گرافیک بهبود یافته و گیم‌پلی جدید",
    icon: <FaGamepad className="text-red-500 text-2xl" />,
    discount: 15,
    inStock: true,
    rating: 4.8
  },
  {
    id: 2,
    name: "تیشرت لئون اس. کندی",
    price: 29.99,
    category: "clothing",
    image: "https://m.media-amazon.com/images/I/61pBwQ4mAXL._AC_UX679_.jpg",
    description: "تیشرت رسمی با طرح لئون اس. کندی از رزیدنت ایول ۲",
    icon: <FaTshirt className="text-blue-500 text-2xl" />,
    discount: 0,
    inStock: true,
    rating: 4.5
  },
  {
    id: 3,
    name: "کتاب هنر رزیدنت ایول - مجموعه کامل",
    price: 45.99,
    category: "books",
    image: "https://images-na.ssl-images-amazon.com/images/I/71UQyO5lqXL.jpg",
    description: "کتاب هنر رسمی شامل طراحی شخصیت‌ها، محیط‌ها و دشمنان",
    icon: <FaBook className="text-yellow-500 text-2xl" />,
    discount: 10,
    inStock: true,
    rating: 4.9
  },
  {
    id: 4,
    name: "ماسک صورت نمسیس",
    price: 19.99,
    category: "accessories",
    image: "https://i.ebayimg.com/images/g/VGAAAOSwzJ5XWCN9/s-l1600.jpg",
    description: "ماسک صورت با طراحی نمسیس از رزیدنت ایول ۳",
    icon: <FaUserAstronaut className="text-purple-500 text-2xl" />,
    discount: 0,
    inStock: true,
    rating: 4.3
  },
  {
    id: 5,
    name: "مجسمه جیل ولنتاین",
    price: 89.99,
    category: "collectibles",
    image: "https://www.bigbadtoystore.com/images/products/out/large/DFC10698.jpg",
    description: "مجسمه کلکسیونی جیل ولنتاین با کیفیت بالا از رزیدنت ایول ۳",
    icon: <FaGem className="text-yellow-500 text-2xl" />,
    discount: 20,
    inStock: true,
    rating: 4.9
  },
  {
    id: 6,
    name: "هودری آر.پی.دی. RPD",
    price: 49.99,
    category: "clothing",
    image: "https://m.media-amazon.com/images/I/71QkQykzOLL._AC_UX569_.jpg",
    description: "هودی رسمی با لوگوی پلیس راکون سیتی (RPD)",
    icon: <FaTshirt className="text-blue-500 text-2xl" />,
    discount: 5,
    inStock: true,
    rating: 4.7
  },
  {
    id: 7,
    name: "فنجان قهوه آمبرلا",
    price: 14.99,
    category: "accessories",
    image: "https://m.media-amazon.com/images/I/61pYpWkIYML._AC_SL1500_.jpg",
    description: "فنجان قهوه با لوگوی شرکت آمبرلا",
    icon: <FaMugHot className="text-amber-600 text-2xl" />,
    discount: 0,
    inStock: true,
    rating: 4.6
  },
  {
    id: 8,
    name: "موسیقی متن رزیدنت ایول - وینیل",
    price: 34.99,
    category: "music",
    image: "https://m.media-amazon.com/images/I/81lEwC5-L7L._AC_SL1500_.jpg",
    description: "موسیقی متن سری رزیدنت ایول روی صفحه وینیل",
    icon: <FaMusic className="text-pink-500 text-2xl" />,
    discount: 0,
    inStock: false,
    rating: 4.8
  },
  {
    id: 9,
    name: "کیسه چرمی S.T.A.R.S.",
    price: 39.99,
    category: "accessories",
    image: "https://m.media-amazon.com/images/I/71WQnLqhvzL._AC_SL1500_.jpg",
    description: "کیسه چرمی با لوگوی تیم S.T.A.R.S.",
    icon: <FaKey className="text-green-500 text-2xl" />,
    discount: 10,
    inStock: true,
    rating: 4.4
  },
  {
    id: 10,
    name: "پوستر کلکسیونی رزیدنت ایول",
    price: 24.99,
    category: "posters",
    image: "https://m.media-amazon.com/images/I/71yqLHVJqQL._AC_SL1500_.jpg",
    description: "پوستر دیواری کلکسیونی با طرح اصلی رزیدنت ایول",
    icon: <FaFilm className="text-indigo-500 text-2xl" />,
    discount: 0,
    inStock: true,
    rating: 4.7
  },
  {
    id: 11,
    name: "دستکش گیمینگ رزیدنت ایول",
    price: 27.99,
    category: "accessories",
    image: "https://m.media-amazon.com/images/I/61gYEj4fczL._AC_SL1500_.jpg",
    description: "دستکش گیمینگ با طرح اختصاصی رزیدنت ایول",
    icon: <FaGamepad className="text-red-500 text-2xl" />,
    discount: 0,
    inStock: true,
    rating: 4.5
  },
  {
    id: 12,
    name: "ساعت دیواری اسپنسر مانشن",
    price: 32.99,
    category: "decor",
    image: "https://images.t-shirt-vault.com/2021/10/Resident-Evil-1-Spencer-Mansion-Clock-3D-Wall-Clock.jpg",
    description: "ساعت دیواری با طراحی عمارت اسپنسر از رزیدنت ایول ۱",
    icon: <FaClock className="text-gray-500 text-2xl" />,
    discount: 15,
    inStock: true,
    rating: 4.6
  },
  {
    id: 13,
    name: "تقویم رومیزی رزیدنت ایول ۲۰۲۵",
    price: 12.99,
    category: "accessories",
    image: "https://m.media-amazon.com/images/I/81QjVUjASUL._AC_SL1500_.jpg",
    description: "تقویم رومیزی با تصاویر اختصاصی از شخصیت‌های رزیدنت ایول",
    icon: <FaCalendarAlt className="text-orange-500 text-2xl" />,
    discount: 0,
    inStock: true,
    rating: 4.2
  },
  {
    id: 14,
    name: "بسته هدیه رزیدنت ایول",
    price: 79.99,
    category: "gifts",
    image: "https://m.media-amazon.com/images/I/71jKpR7bVXL._AC_SL1500_.jpg",
    description: "بسته هدیه شامل ۵ محصول مختلف رزیدنت ایول",
    icon: <FaGift className="text-red-500 text-2xl" />,
    discount: 25,
    inStock: true,
    rating: 4.9
  },
  {
    id: 15,
    name: "جعبه کلکسیونی رزیدنت ایول",
    price: 149.99,
    category: "collectibles",
    image: "https://m.media-amazon.com/images/I/81pVhK+qjML._AC_SL1500_.jpg",
    description: "جعبه کلکسیونی محدود شامل مجسمه، پوستر، کتاب و محصولات انحصاری",
    icon: <FaBox className="text-purple-500 text-2xl" />,
    discount: 30,
    inStock: true,
    rating: 5.0
  }
];